from Arvore.arvore import Arvore

arvore = Arvore()
arvore.add(10)
arvore.add(18)
arvore.add(5)
arvore.add(15)
arvore.add(4)
arvore.add(8)
arvore.add(9)
arvore.add(7)
arvore.add(6)
arvore.add(21)
arvore.add(17)
arvore.add(16)
print("---------------")
print("Altura:",arvore.get_altura())
print("Altura:",arvore.get_altura(15))
print("Altura:",arvore.get_altura(18))
print("Nível:",arvore.get_nivel())
print("Nível:",arvore.get_nivel(15))
print("Nível:",arvore.get_nivel(18))
print("Nível:",arvore.get_nivel(5))

print(arvore.sucessor())
print(arvore.sucessor(15))
print(arvore.predecessor())
print(arvore.predecessor(18))
print("Tamanho",arvore.tamanho())
arvore.remove_valor(9)
arvore.remove_valor(18)
arvore.remove_valor(10)
arvore.remove_valor(5)
print(arvore.is_get_dado(9))
print(arvore.is_get_dado(18))
print(arvore.is_get_dado(7))
print(arvore.is_get_dado(5))
print("Tamanho",arvore.tamanho())